baseURL = "https://oronerostudio.github.io/"
theme = "up-business-theme"
languageCode = "en-us"
title = "Oronero Studio"
summaryLength = 20

[params]
title = "Oronero Studio"
description = "We focus on combining fresh ideas with quality to create engaging mobile games."
images = [ "images/hero-image.png" ]
logo = "images/hero-image.png"
# location = [ "3891 Ranchview Dr. Richardson, California 62639" ]
# contact = [ "trungkienspktnd@gamail.com", "207.555.0119" ]
copyright = "© 2022 Oronero Studio All Rights Reserved. Google Play and the Google Play logo are trademarks of Google LLC."
postProcess = false

  [params.favicons]
  themeColor = "#FFFFFF"
  backgroundColor = "#FFFFFF"
  faviconColor = "#000000"

#   [params.social]
#   dribbble = "#"
#   instagram = "#"
#   facebook = "#"
#   twitter = "#"

# [[menus.main]]
# name = "Home"
# url = "/#hero"
# weight = 1

# [[menus.buttons]]
# name = "Book a call"
# url = "/#"
# weight = 5
# pre = "btn btn-primary text-light"

[[menus.footer]]
name = "Home"
url = "/#hero"
weight = 1

[taxonomies]
series = "series"
tags = "tags"
